<a href="https://colab.research.google.com/github/MariaElisaOliveiraMartins/Curso_DS_Pro/blob/main/Aula3_(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estruturas de dados em Python => Criando objetos simples e complexos


### Variáveis => Posições de memória que armazemam dados. 

In [139]:
x = 3
nome = "Mauro"
logica = True

In [140]:
nome1 = "Mauro"
nome2 = "Bete"
nome3 = "Pedro"

### Listas => são conjuntos de dados cujos elementos podem ser alterados.



In [141]:
nomes = ["Mauro","Pedro", "Bete"] 
print(nomes)
nomes = [nome1,nome2,nome3]
print(nomes)
nomes.append("João")
print(nomes)

['Mauro', 'Pedro', 'Bete']
['Mauro', 'Bete', 'Pedro']
['Mauro', 'Bete', 'Pedro', 'João']


In [142]:
nomes.remove("Mauro")
print(nomes)
#nomes.remove("Maria")

['Bete', 'Pedro', 'João']


In [143]:
"Maria" in nomes

False

In [144]:
if "Maria" in nomes:
  nomes.remove("Maria")
else:
  print("Não tem Maria em nomes")


Não tem Maria em nomes


In [145]:
for nome in nomes:
  print(nome)

Bete
Pedro
João


## Tuplas => Também são conujunto de dados, porém seus elementos não podem ser alterados.


In [146]:
primos = (1,2,3,5,7,11,13,17,23)
print(primos)
primo_par = 2,
print(primo_par)

(1, 2, 3, 5, 7, 11, 13, 17, 23)
(2,)




```
# Isto está formatado como código
```

## Dicionários => Armazenamento randômico para estrutura de dados.

In [147]:
comida = {}

In [148]:
comida["feijoada"] = "Minha comida preferida"
comida["coentro"] = "Vixi, detesto!"
comida

{'coentro': 'Vixi, detesto!', 'feijoada': 'Minha comida preferida'}

In [149]:
comida["coentro"]

'Vixi, detesto!'

In [150]:
comida["queijo"] = "Uai, sou mineiro!"

In [151]:
print(comida)

{'feijoada': 'Minha comida preferida', 'coentro': 'Vixi, detesto!', 'queijo': 'Uai, sou mineiro!'}


In [152]:
if 'queijo' in comida:
  print("O que eu acho de queijo é: ")
  print(comida["queijo"])

O que eu acho de queijo é: 
Uai, sou mineiro!


In [153]:
del comida["coentro"]

In [154]:
print(comida)

{'feijoada': 'Minha comida preferida', 'queijo': 'Uai, sou mineiro!'}


In [155]:
for key in comida:
  print(key,' -> ',comida[key])

feijoada  ->  Minha comida preferida
queijo  ->  Uai, sou mineiro!


In [156]:
pares = (2, 4, 6, 8, 10)
impares = (1, 3, 5, 7, 9)
numeros = {}
numeros['pares'] = pares
numeros['impares'] = impares
print (numeros)

{'pares': (2, 4, 6, 8, 10), 'impares': (1, 3, 5, 7, 9)}


## Combinando estruturas de dados => Dicionário de tuplas de listas (objetos complexos).



In [157]:
eu = {"família" : nomes,
      "comidas" : comida}

In [158]:
print(eu)

{'família': ['Bete', 'Pedro', 'João'], 'comidas': {'feijoada': 'Minha comida preferida', 'queijo': 'Uai, sou mineiro!'}}


## Outros exemplos em estrutura de dados => Identificando tipos de dados dos objetos complexos.




In [159]:
 print(sorted(nomes))

['Bete', 'João', 'Pedro']


In [160]:
print(type(nome1))
print(type(nomes))
print(type(primos))
print(type(eu))

<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


## Pandas => Importação da biblioteca. 

In [161]:
import pandas as pd
from pandas import Series, DataFrame

## Série => Método da biblioteca Pandas para tratamento de séries de dados.

In [162]:
ser_1 = Series([1, 1, 2, -3, -5, 8, 13]) # Cria de uma série cuja estrutura se assemelha aos vetores/lista de dados c/ os índices e seus conteúdos.
ser_1                                    # Exibe os índices com seus respectivos conteúdos.

0     1
1     1
2     2
3    -3
4    -5
5     8
6    13
dtype: int64

In [163]:
print(ser_1.index)  # Exibe a estrutura dos índices da série.
print(ser_1.values) # Exibe os valores da série.


RangeIndex(start=0, stop=7, step=1)
[ 1  1  2 -3 -5  8 13]


In [164]:
ser_teste = Series([1, 1, 2, -3, -5], index=['a', 'b', 'c', 'd', 'e']) # Cria uma série definindo os índices.
print(ser_teste.index)  # Exibe a estrutura dos índices da série.
print(ser_teste.values) # Exibição os valores da série.

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[ 1  1  2 -3 -5]


In [165]:
ser_2 = Series([1, 1, 2, -3, -5], index=['a', 'b', 'c', 'd', 'e']) # Cria identificadores para os índices da série.
ser_2 # Exibição do conteúdo da série.

a    1
b    1
c    2
d   -3
e   -5
dtype: int64

In [166]:
ser_2['d'] # Exibe o conteúdo (valor) do elemento indicado pelo identificador especificado.

-3

In [167]:
ser_2[4] == ser_2['e'] # Compara o valor do elemento especificado pelo identificador atribuído à série com o conteúdo especificado pelo índice da série.

True

In [168]:
ser_2[['c', 'a', 'b']] # Exibe um subconjunto da séire cujos identificadores são especificados como uma lista de índices. 

c    2
a    1
b    1
dtype: int64

In [169]:
ser_2[ser_2 > 0] # Exibe um subconjunto da série cujos valores satisfazem a condição especificada no índice (filtro). 

a    1
b    1
c    2
dtype: int64

In [170]:
ser_2 * (10 - 4) / 2 + 1 # Efetua a operação aritmética especificada sobre os elementos da série.

a     4.0
b     4.0
c     7.0
d    -8.0
e   -14.0
dtype: float64

## NunPy => Importação da biblioteca.

In [171]:
import numpy as np # Importa a biblioteca.
np.exp(ser_2)      # Aplica o exponecial e**x sobre os elementos da série onde cada elemento da série é o expoente da função.

a    2.718282
b    2.718282
c    7.389056
d    0.049787
e    0.006738
dtype: float64

In [172]:
ser_3 = Series(eu) # Converte uma estrutura complexa (um dicionário de lista e tuplas) em uma série.
ser_3              # Exibe o conteúdo e o formato da estrutura.

família                                  [Bete, Pedro, João]
comidas    {'feijoada': 'Minha comida preferida', 'queijo...
dtype: object

In [173]:
pd.isnull(ser_3) # Verifica a existencia de nulos (NaN) na série.

família    False
comidas    False
dtype: bool

## Dataframe => Utilização da biblioteca Pandas

In [174]:
info = {'estado' : ['MG', 'MG', 'MG', 'SP', 'SP'],
        'ano' : [2012, 2013, 2014, 2014, 2015],
        'pop' : [5.0, 5.1, 5.2, 4.0, 4.1]}       # Cria uma estrutura complexa de dados (objeto = dicionário de tuplas de listas).
print(type(info))                                # Exibe o tipo do objeto.
df = DataFrame(info)                             # Converte o objeto criado em um dataframde do Pandas.
print(type(df))                                  # Exibe o tipo do objeto criado pelo Pandas.
print(df)                                        # Exibe o conteúdo do objeto (dataframe).

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
  estado   ano  pop
0     MG  2012  5.0
1     MG  2013  5.1
2     MG  2014  5.2
3     SP  2014  4.0
4     SP  2015  4.1


In [175]:
df = DataFrame(info, columns=['ano', 'estado', 'pop', 'desempregados']) # Acrescenta nova coluna ao dataframe.
df

ano estado  pop desempregados
0  2012     MG  5.0           NaN
1  2013     MG  5.1           NaN
2  2014     MG  5.2           NaN
3  2014     SP  4.0           NaN
4  2015     SP  4.1           NaN

In [176]:
print(df['ano'])          # Exibe uma coluna específica do dataframe tratando a mesma como um vetores. 
print(df.desempregados)   # Exibe uma coluna específica do dataframe tratando a mesma como um objeto.

0    2012
1    2013
2    2014
3    2014
4    2015
Name: ano, dtype: int64
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: desempregados, dtype: object


In [177]:
df.iloc[4] # Exibe o conteúdo da linha do dataframe indicada pelo índice especificado no método "iloc".  

ano              2015
estado             SP
pop               4.1
desempregados     NaN
Name: 4, dtype: object

In [178]:
type(df.iloc[4])  # Exibe o tipo da linha indicada na função "iloc" (obs: como os tipos das colunas em um dataframe variam, as linhas tornam-se séries).

pandas.core.series.Series

In [179]:
df.desempregados = np.random.rand(5) * 1000000 # Atribui valor à coluna "desempregados" usando uma função randômica para gerar 5 números aleatórios e multiplica-los por um valor escalar (1 milhão). 
df

ano estado  pop  desempregados
0  2012     MG  5.0  445660.588815
1  2013     MG  5.1   19975.898582
2  2014     MG  5.2  245256.294470
3  2014     SP  4.0  687059.804890
4  2015     SP  4.1  584159.352718

In [180]:
df.desempregados = df.desempregados.astype(int) # Converte o tipo da coluna "desempregados" (de real para inteiro).
df

ano estado  pop  desempregados
0  2012     MG  5.0         445660
1  2013     MG  5.1          19975
2  2014     MG  5.2         245256
3  2014     SP  4.0         687059
4  2015     SP  4.1         584159

In [181]:
desempregados = Series([454333, 232111, 242422], index=[2, 3, 4]) # Cria uma série (objeto) definindo valores e índices. 
df.desempregados = desempregados                                  # Atribui o conteúdo da série criada sobre parte da coluna do dataframe (correspondente aos índices).
df

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [182]:
df['nonsense'] = df.ano * df.desempregados # Cria uma nova coluna (ridúcula) no dataframe (obs: só pra apagar depois... KKKK!)
df

ano estado  pop  desempregados     nonsense
0  2012     MG  5.0            NaN          NaN
1  2013     MG  5.1            NaN          NaN
2  2014     MG  5.2       454333.0  915026662.0
3  2014     SP  4.0       232111.0  467471554.0
4  2015     SP  4.1       242422.0  488480330.0

In [183]:
del df['nonsense']  # Remove a coluna criada (KKKK!) 
df

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [184]:
df2 = df[['ano','pop']]   # Cria um novo dataframe composto por um subconjunto de colunas do dataframe original (obs: o índice do dataframe é uma lista de colunas).
df2

ano  pop
0  2012  5.0
1  2013  5.1
2  2014  5.2
3  2014  4.0
4  2015  4.1

In [185]:
df2.T # Exibe a transposição do dataframe (função "T" = tranposição da matrizes).

0       1       2       3       4
ano  2012.0  2013.0  2014.0  2014.0  2015.0
pop     5.0     5.1     5.2     4.0     4.1

In [186]:
df.values  # Exibe o dataframe como um array de listas.

array([[2012, 'MG', 5.0, nan],
       [2013, 'MG', 5.1, nan],
       [2014, 'MG', 5.2, 454333.0],
       [2014, 'SP', 4.0, 232111.0],
       [2015, 'SP', 4.1, 242422.0]], dtype=object)

In [187]:
type(df.values) # Confirma o tipo do retorno (exibição) da função "values".

numpy.ndarray

In [188]:
df2 = df.copy() # Copia o conteúdo do dataframe original criando um novo dataframe (obs: sem a função "copy" o novo objeto faz apenas uma referencia ao objeto original).
df.drop([0, 1]) # Elimina as linhas indicadas pela lista de índices (dataframe original).

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [189]:
df2

ano estado  pop  desempregados
0  2012     MG  5.0            NaN
1  2013     MG  5.1            NaN
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [190]:
df2.ano > 2013  # Aplica um filtro sobre uma coluna do dataframe exibindo/retornando o valor booleano resultante da expressão lógica. 

0    False
1    False
2     True
3     True
4     True
Name: ano, dtype: bool

In [191]:
df2[df2.ano > 2013]  # Aplica um filtro sobre as linhas do dataframe exibindo/retornando aquelas que satisfazem a condição da expressão lógica.

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0
4  2015     SP  4.1       242422.0

In [192]:
df2.iloc[2:4]  # Exibe as linhas do dataframe indicadas no intervalo entre os índices da função "iloc" (o útimo índice é "exclusive").

ano estado  pop  desempregados
2  2014     MG  5.2       454333.0
3  2014     SP  4.0       232111.0

In [193]:
df2.iloc[2:4].estado # Exibe o resultado de uma combinação de filtros (aplicados às linhas e colunas simultâneamente).

2    MG
3    SP
Name: estado, dtype: object

## Numpy arrays

### Criando arrays

In [194]:
import numpy as np

a = np.array([1, 2, 3])   # Cria um vetor (array) simples com 3 elementos.
print(type(a))            # Exibe o tipo do vetor.    
print(a.shape)            # Exibe a dimensão do vetor.
print(a[0], a[1], a[2])   # Exibe os elementos do vetor um a um explicitando seus índices.
a[0] = 5                  # Atribui um valor a um elemento do vetor explicitando o seu índice.
print(a)                  # Exibe o vetor atualizado.

b = np.array([[1,2,3],[4,5,6]])    # Cria uma matriz (array de arrays).
print(b)                           # Exibe o conteúdo da matriz (elementos).
print(b.shape)                     # Exibe a dimensão da matriz.
print(b[0, 0], b[0, 1], b[1, 0])   # Exibe os elementos da matriz um a um explicitando seus índices.

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [195]:
a = np.zeros((2,2))   #Cria matriz 2 X 2 preenchida com zeros.
print(a)              
                      

b = np.ones((1,2))    # Cria matriz 1 X 2 preenchida com "1s"
print(b)              

c = np.full((2,2), 7) # Cria matriz 2 X 2 preenchida com "7s" (constante).
print(c)               
                       

d = np.eye(3)         # Cria uma matriz-identidade (matriz quadrada cuja diagonal princial é preenchida com "1s" e o restante com "0s") de dimensão 3 X 3.
print(d)              

e = np.random.random((2,2))  # Cria uma matriz 2 X 2 com números aleatórios.
print(e)                     
                             

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.80931021 0.1737391 ]
 [0.73415356 0.36666326]]


### Indexando arrays

In [196]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # Cria matriz 3 X 4.
print(a)

# Usando slicing para obter sub-array com as primeiras 2 linhas
# e as colunas 1 e 2

b = a[:2, 1:3]    # Abribui para "b" um recorte da matriz "a" de dimensão 2 X 2 (linhas 0 e 1 , colunas 1 e 2).
print(b)

# Uma fatia de um array é uma VISÃO desse mesmo array. Isso significa
# que modificar um elemento de "b" mudará o valor em "a".

print(a[0, 1])    # Exibe o elemento da primeira linha e segunda coluna da matriz "a".
b[0, 0] = 77      # Atribui o valor "77" ao elemento da primeira linha e primeira coluna na matriz "b" gerada a partir de "a".
print(a[0, 1])    # 

c = a[:2, 1:3].copy()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[77  3]
 [ 6  7]]


In [197]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # Cria matriz 3 X 4.
print(a)

# Usando slicing para obter sub-array com as primeiras 2 linhas
# e as colunas 1 e 2

b = a[:2, 1:3]    # Abribui para "b" um recorte da matriz "a" de dimensão 2 X 2 (linhas 0 e 1 , colunas 1 e 2).
print(b)

# Uma fatia de um array é uma VISÃO desse mesmo array. Isso significa
# que modificar um elemento de "b" mudará o valor em "a".

print(a[0, 1])    # Exibe o elemento da primeira linha e segunda coluna da matriz "a".
b[0, 0] = 77      # Atribui o valor "77" ao elemento da primeira linha e primeira coluna na matriz "b" gerada a partir de "a".
print(a[0, 1])    # 

c = a[:2, 1:3].copy()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[77  3]
 [ 6  7]]


In [198]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # Cria matriz 3 X 4.
print(a)

# Usando slicing para obter sub-array com as primeiras 2 linhas
# e as colunas 1 e 2

b = a[:2, 1:3]    # Abribui para "b" um recorte da matriz "a" de dimensão 2 X 2 (linhas 0 e 1 , colunas 1 e 2).
print(b)

# Uma fatia de um array é uma VISÃO desse mesmo array. Isso significa
# que modificar um elemento de "b" mudará o valor em "a".

print(a[0, 1])    # Exibe o elemento da linha 0 (primeira linha) e coluna 1 (segunda coluna) da matriz "a".
b[0, 0] = 77      # Atribui o valor "77" ao elemento da primeira linha e primeira coluna na matriz "b" (gerada a partir de "a").
print(a[0, 1])    # Exibe novamente o elemento da linha 0 (primeira linha) e coluna 1 (segunda coluna) da matriz "a", demonstrando que o mesmo foi modificado.

c = a[:2, 1:3].copy()  # Cria um novo objeto "c", do tipo matriz, atribuindo a ele uma cópia do recorte de "a".
print(c)               # Exibe a nova matriz.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[77  3]
 [ 6  7]]


In [199]:
c[0, 0] = -1000       # Atribui um novo elemento à nova matriz "c" (primeira linha e primeira coluna = 0 X 0).
print(c)              # Exibe o conteúdo da nova matriz "c".
print(a)              # Exibe o conteúdo da matriz original ("a").

[[-1000     3]
 [    6     7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [200]:
print (a)            # Exibe o conteúda da matriz "a".
a > 10               # Exibe uma visão (espelho) da matriz "a" cujos elementos corresponde ao resultado da expressão indicada. 

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [201]:
print (a)         # Exibe o conteúdo da matriz "a".
a[a > 10]         # Exibe os elementos da matriz "a" que satisfazem a expressão indicada.

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([77, 11, 12])

### Operações com arrays

In [202]:
x = np.array([[1,2],[3,4]], dtype=np.float64)  # Cria a matriz x com valores numéricos reais.
y = np.array([[5,6],[7,8]], dtype=np.float64)  # Cria a matriz y com valores numéricos reais.

print(x + y)       # Soma cada elemento de "x" ao correspondente elemento em "y" (soma dos elementos das mesmas posições nas duas matrizes). 
print(x - y)       # Subtrai de cada elemento de "x" o correspondente elemento em "y" (subtração dos elementos das mesmas posições nas duas matrizes). 
print(x * y)       # Multiplica cada elemento de "x" ao correspondente elemento em "y" (multiplicação entre os elementos das mesmas posições nas duas matrizes). 
print(x / y)       # Divide cada elemento de "x" pelo correspondente elemento em "y" (divisão entre os elementos das mesmas posições nas duas matrizes). 
print(np.sqrt(x))  # Extrai a raiz quadrada de cada um dos elementos da matriz "x".


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [203]:
print(np.dot(x, y))  # Efetua a multiplicação (matemática) entre as matrizes "x" e "y" (não entre os elementos) utilizando a função "dot". 

[[19. 22.]
 [43. 50.]]


In [204]:
print (x)                       # Exibe a matriz "x".
print(np.sum(x))                # Retorna o somatório entre todos os elementos da matriz "x".
print(np.sum(x, axis=0))        # Retorna o somatório entre todos os elementos de cada uma das colunas de "x" (somatório vertical).
print(np.sum(x, axis=1))        # Retorna o somatório entre todos os elementos de cada uma das linhas de "x" (somatório horizontal).

[[1. 2.]
 [3. 4.]]
10.0
[4. 6.]
[3. 7.]


### Exercício => Acessar o meu Google Drive para obter uma imagem do Kiko e exibir um pixel da imagem! 

In [205]:
from google.colab import drive  # Acessa o Google Drive.
drive.mount("/content/drive")   # Monta o meu Drive na minha partição.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [206]:
!ls drive/'My Drive'/Dados_DS/Foto_do_Kiko.jpg # Lista o conteúdo da pasta do Kiko no meu Drive.

'drive/My Drive/Dados_DS/Foto_do_Kiko.jpg'


In [207]:
!pip install Pillow   # Instala a biblioteca Pillow (manipulação de imagens).


In [212]:
from PIL import Image                                         # Importa a Biblioteca Pillow.
img = Image.open("/content/drive/My Drive/Dados_DS/Foto_do_Kiko.jpg")     # Acessa a foto do Kiko a partir do meu Drive.

In [213]:
print(type(img))             # Exibe o tipo do arquivo (foto).
imgnp = np.array(img)        # Carrega o arquivo (foto do kiko) em um objeto (array de 3 dimensões) utilizando o Numpy.
print(type(imgnp))           # Exibe o tipo do objeto criado.

<class 'PIL.JpegImagePlugin.JpegImageFile'>
<class 'numpy.ndarray'>


In [210]:
print(imgnp.shape)           # Exibe a dimensão do objeto (array de pixels com 3 dimessões).

(600, 800, 3)


In [211]:
imgnp[100,200]                 # Exibe os dados da coloração de um pontinho (pixel) da foto do Kiko!  

array([253, 255, 252], dtype=uint8)